# Generated by Django 4.2.6 on 2023-10-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_comment', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=1024)),
                ('comment', models.ManyToManyField(to='main.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_created=True)),
                ('picture', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=5096)),
                ('comments', models.ManyToManyField(to='main.comment')),
            ],
        ),
    ]
