# Generated by Django 4.2.6 on 2023-10-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_comment_alter_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_comment',
        ),
    ]
